name = "XPlot"
uuid = "05f8af49-9276-49ac-91ff-a5ea52b3fe06"
authors = ["Jack <jackgarbus@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
